### ISSUE TITLE
Adaptation field skipping

### ISSUE THREAD

**Issue by ahenshaw** [GrimOutlook/ts-reader#1]
It appears that there is a bug in the code to skip over an adaptation field (if present).  You read the field length and then increment the _read_idx_ by that value.  However, you need to skip over one more byte in order to accommodate the length field itself.  So, line 70 of packet.rs should be:
`read_idx += af.adaptation_field_length() as usize + 1;`

Would you like me to submit a merge request or would you prefer to just make that small change?

**Comment by GrimOutlook** [comment]
Feel free to make a merge request. I can take a look and add it in. Good catch!

**Comment by GrimOutlook** [comment]
Actually, it looks like I fixed that bug in the feature/incorrect_payload branch. Let me merge that in and put out a new version.

**Comment by GrimOutlook** [comment]
I had some code laying around that had that fix in it. It has some additional testing items in it as well when I was trying to debug why the KLV data I was getting was incorrect as well. I will merge it in and it will be available in version 0.2.1
